name: Authentication Web Api Pipeline
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Checking Out
      uses: actions/checkout@v2
    - name: Installing .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.102
        include-prerelease: true
    - name: Restoring Nuget Packages
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Running Tests
      run: dotnet test --no-build --verbosity normal
